spring:
  application:
    name: sport-complex-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sport_complex_db
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${PORT:0}
eureka:
  instance:
    instance-id:${spring.application.name}:${random.value}
  client:
    service-url:
          defaultZone: http://localhost:8761/eureka

routefile: C:\Users\USUARIO\Desktop\content-file

